browser_profile: C:\Temp\ClaudeProfile
claude_url: https://claude.ai
debug: false
delay_between_prompts: 3
max_retries: 3
max_retry_delay: 30
ocr:
  config: --psm 6
  contrast_enhance: true
  denoise: true
  engine: tesseract
  preprocess: true
prompts:
- Summarize the latest AI trends.
- Explain how reinforcement learning works.
- Write a Python function that reverses a string.
response_timeout: 60
retry_backoff: 1.5
retry_delay: 2
retry_jitter: 0.5
ui_elements:
  prompt_box:
    confidence: 0.7
    reference_paths:
    - assets/reference_images/prompt_box\prompt_box_1746343792.png
    region: !!python/tuple
    - !!python/object/apply:numpy.core.multiarray.scalar
      - &id001 !!python/object/apply:numpy.dtype
        args:
        - i8
        - false
        - true
        state: !!python/tuple
        - 3
        - <
        - null
        - null
        - null
        - -1
        - -1
        - 0
      - !!binary |
        agYAAAAAAAA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        hgQAAAAAAAA=
    - 434
    - 186
  response_area:
    confidence: 0.7
    reference_paths: []
    region: !!python/tuple
    - 0
    - 0
    - 2560
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        aAQAAAAAAAA=
  send_button:
    confidence: 0.7
    reference_paths:
    - assets/reference_images/send_button\send_button_1746343937.png
    region: !!python/tuple
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        /wEAAAAAAAA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        NQQAAAAAAAA=
    - 80
    - 80
  thinking_indicator:
    confidence: 0.6
    reference_paths:
    - assets/reference_images/thinking_indicator\thinking_1746343973.png
    region: !!python/tuple
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        tggAAAAAAAA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        MQAAAAAAAAA=
    - 200
    - 160
