browser_profile: C:\Temp\ClaudeProfile
claude_url: https://claude.ai
debug: false
prompts:
- Summarize the latest AI trends.
- Explain how reinforcement learning works.
- Write a Python function that reverses a string.
ui_elements:
  prompt_region:
    confidence: 0.7
    reference_paths: []
    region: !!python/tuple
    - 536
    - 722
    - 1615
    - 634
