browser_profile: C:\Temp\ClaudeProfile
claude_url: https://claude.ai
debug: false
prompts:
- Summarize the latest AI trends.
- Explain how reinforcement learning works.
- Write a Python function that reverses a string.
ui_elements:
  prompt_box:
    confidence: 0.7
    reference_paths:
    - assets/reference_images/prompt_box\prompt_box_1_1746403024.png
    - assets/reference_images/prompt_box\prompt_box_1_1746404009.png
    - assets/reference_images/prompt_box\prompt_box_2_1746403033.png
    - assets/reference_images/prompt_box\prompt_box_4_1746404014.png
    - assets/reference_images/prompt_box\prompt_box_5_1746404084.png
    - assets/reference_images/prompt_box\prompt_box_6_1746404088.png
    - assets/reference_images/prompt_box\prompt_box_7_1746404094.png
    region:
    - 635
    - 745
    - 1800
    - 607
  send_button:
    confidence: 0.7
    reference_paths:
    - assets/reference_images/send_button\send_button_1_1746404204.png
    - assets/reference_images/send_button\send_button_2_1746404231.png
    region:
    - 1910
    - 867
    - 513
    - 470
