browser_profile: C:\Temp\ClaudeProfile
claude_url: https://claude.ai
debug: false
prompts:
- Summarize the latest AI trends.
- Explain how reinforcement learning works.
- Write a Python function that reverses a string.
ui_elements:
  prompt_region:
    confidence: 0.7
    reference_paths:
    - assets/reference_images/prompt_region\prompt_region_1_1746403024.png
    - assets/reference_images/prompt_region\prompt_region_2_1746403033.png
    region: !!python/tuple
    - 817
    - 679
    - 1597
    - 680
