browser_profile: C:\Temp\ClaudeProfile
claude_url: https://claude.ai/project/019699e5-0fdf-75f1-9190-3b4cc593bc9e
debug: true
debug_settings:
  log_clicks: true
  log_recognition: true
  save_screenshots: true
  verbose_output: true
delay_between_prompts: 3
max_retries: 3
max_retry_delay: 30
ocr:
  config: --psm 6
  contrast_enhance: true
  denoise: true
  engine: tesseract
  preprocess: true
prompts:
- How can I update this so instead of looking for the thinking icon, the program doesn't
  send another prompt unless it sees the send button again
- Identify functions or files that are overly complex or too long.
response_timeout: 60
retry_backoff: 1.5
retry_delay: 2
retry_jitter: 0.5
ui_elements:
  extended_thought:
    confidence: 0.7
    reference_paths:
    - assets/reference_images/extended_thought/extended_thought_1746422413.png
    - assets/reference_images/extended_thought\extended_thought_1746422413_gray.png
    - assets/reference_images/extended_thought\extended_thought_1746422413_contrast.png
    - assets/reference_images/extended_thought\extended_thought_1746422413_thresh.png
    region:
    - 280
    - 939
    - 621
    - 64
  limit_reached:
    confidence: 0.7
    reference_paths:
    - assets/reference_images/limit_reached/limit_reached_1746424723.png
    - assets/reference_images/limit_reached\limit_reached_1746424723_gray.png
    - assets/reference_images/limit_reached\limit_reached_1746424723_contrast.png
    - assets/reference_images/limit_reached\limit_reached_1746424723_thresh.png
    - assets/reference_images/limit_reached/limit_reached_1746424729.png
    - assets/reference_images/limit_reached\limit_reached_1746424729_gray.png
    - assets/reference_images/limit_reached\limit_reached_1746424729_contrast.png
    - assets/reference_images/limit_reached\limit_reached_1746424729_thresh.png
    region:
    - 141
    - 1044
    - 1124
    - 89
  prompt_box:
    confidence: 0.9
    reference_paths:
    - assets/reference_images/prompt_box\prompt_box_1_1746403024.png
    - assets/reference_images/prompt_box\prompt_box_1_1746404009.png
    - assets/reference_images/prompt_box\prompt_box_2_1746403033.png
    - assets/reference_images/prompt_box\prompt_box_4_1746404014.png
    - assets/reference_images/prompt_box\prompt_box_5_1746404084.png
    - assets/reference_images/prompt_box\prompt_box_6_1746404088.png
    - assets/reference_images/prompt_box\prompt_box_7_1746404094.png
    - assets/reference_images/prompt_box\prompt_box_1_1746403024_gray.png
    - assets/reference_images/prompt_box\prompt_box_1_1746403024_contrast.png
    - assets/reference_images/prompt_box\prompt_box_1_1746403024_thresh.png
    - assets/reference_images/prompt_box\prompt_box_1_1746404009_gray.png
    - assets/reference_images/prompt_box\prompt_box_1_1746404009_contrast.png
    - assets/reference_images/prompt_box\prompt_box_1_1746404009_thresh.png
    - assets/reference_images/prompt_box\prompt_box_2_1746403033_gray.png
    - assets/reference_images/prompt_box\prompt_box_2_1746403033_contrast.png
    - assets/reference_images/prompt_box\prompt_box_2_1746403033_thresh.png
    - assets/reference_images/prompt_box\prompt_box_4_1746404014_gray.png
    - assets/reference_images/prompt_box\prompt_box_4_1746404014_contrast.png
    - assets/reference_images/prompt_box\prompt_box_4_1746404014_thresh.png
    - assets/reference_images/prompt_box\prompt_box_5_1746404084_gray.png
    - assets/reference_images/prompt_box\prompt_box_5_1746404084_contrast.png
    - assets/reference_images/prompt_box\prompt_box_5_1746404084_thresh.png
    - assets/reference_images/prompt_box\prompt_box_6_1746404088_gray.png
    - assets/reference_images/prompt_box\prompt_box_6_1746404088_contrast.png
    - assets/reference_images/prompt_box\prompt_box_6_1746404088_thresh.png
    - assets/reference_images/prompt_box\prompt_box_7_1746404094_gray.png
    - assets/reference_images/prompt_box\prompt_box_7_1746404094_contrast.png
    - assets/reference_images/prompt_box\prompt_box_7_1746404094_thresh.png
    region:
    - 146
    - 521
    - 1958
    - 827
  response_area:
    confidence: 0.8
    reference_paths:
    - assets/reference_images/response_area\response_area_1.png
    - assets/reference_images/response_area\response_area_1_1746405848.png
    - assets/reference_images/response_area\response_area_1_gray.png
    - assets/reference_images/response_area\response_area_1_contrast.png
    - assets/reference_images/response_area\response_area_1_thresh.png
    - assets/reference_images/response_area\response_area_1_1746405848_gray.png
    - assets/reference_images/response_area\response_area_1_1746405848_contrast.png
    - assets/reference_images/response_area\response_area_1_1746405848_thresh.png
    region:
    - 526
    - 269
    - 1627
    - 853
  search_options_button:
    confidence: 0.7
    reference_paths:
    - assets/reference_images/search_options_button/search_options_button_1746421759.png
    - assets/reference_images/search_options_button\search_options_button_1746421759_gray.png
    - assets/reference_images/search_options_button\search_options_button_1746421759_contrast.png
    - assets/reference_images/search_options_button\search_options_button_1746421759_thresh.png
    region:
    - 258
    - 711
    - 92
    - 86
  send_button:
    confidence: 0.8
    reference_paths:
    - assets/reference_images/send_button\send_button_1_1746404204.png
    - assets/reference_images/send_button\send_button_2_1746404231.png
    - assets/reference_images/send_button\send_button_1_1746404204_gray.png
    - assets/reference_images/send_button\send_button_1_1746404204_contrast.png
    - assets/reference_images/send_button\send_button_1_1746404204_thresh.png
    - assets/reference_images/send_button\send_button_2_1746404231_gray.png
    - assets/reference_images/send_button\send_button_2_1746404231_contrast.png
    - assets/reference_images/send_button\send_button_2_1746404231_thresh.png
    region:
    - 1416
    - 636
    - 684
    - 706
  thinking_indicator:
    confidence: 0.8
    reference_paths:
    - assets/reference_images/thinking_indicator\thinking_indicator_1.png
    - assets/reference_images/thinking_indicator\thinking_indicator_1_1746405241.png
    - assets/reference_images/thinking_indicator\thinking_indicator_1_gray.png
    - assets/reference_images/thinking_indicator\thinking_indicator_1_contrast.png
    - assets/reference_images/thinking_indicator\thinking_indicator_1_thresh.png
    - assets/reference_images/thinking_indicator\thinking_indicator_1_1746405241_gray.png
    - assets/reference_images/thinking_indicator\thinking_indicator_1_1746405241_contrast.png
    - assets/reference_images/thinking_indicator\thinking_indicator_1_1746405241_thresh.png
    region:
    - 1960
    - 1239
    - 94
    - 87
